/**
 * SimSN Live Data — Alabama Crimson Tide 2026
 * Loads data/alabama.json (written daily by GitHub Actions).
 * Falls back to the SimSN API directly if the file is unavailable.
 */
const SimSN = (() => {
  const LOCAL  = 'data/alabama.json';
  const API    = 'https://simbaseballapi-production.up.railway.app/api/v1';
  const ORG    = 34;
  const TEAM   = 184;
  const SEC    = 'Southeastern Conference';

  let _data = null;

  // ── Fetch ─────────────────────────────────────────────────────────────────

  async function load() {
    if (_data) return _data;
    // Try local data file first (fast, generated by GitHub Actions daily)
    try {
      const r = await fetch(LOCAL);
      if (r.ok) { _data = await r.json(); return _data; }
    } catch (_) {}
    // Fall back to live API
    try {
      const r = await fetch(`${API}/bootstrap/landing/${ORG}?viewing_org_id=${ORG}`);
      if (!r.ok) throw new Error(r.status);
      _data = _transform(await r.json());
      return _data;
    } catch (e) {
      console.warn('[SimSN] Data unavailable:', e.message);
      return null;
    }
  }

  function _transform(raw) {
    const teamMap = {};
    for (const t of (raw.AllTeams || [])) teamMap[t.team_id] = t;

    const rosterRaw = raw.RosterMap?.[String(TEAM)] || [];
    const roster = rosterRaw.map(p => {
      const rat = p.ratings || {};
      const pot = p.potentials || {};
      const yr  = p.contract?.current_year ?? 4;
      const pos = p.listed_position || (p.ptype === 'Pitcher' ? 'SP' : '?');
      return {
        id: p.id,
        firstname: p.firstname, lastname: p.lastname,
        ptype: p.ptype, pos,
        ovr: p.displayovr,
        ovr_grade: numToGrade(p.displayovr),
        year: yr, year_label: {1:'FR',2:'SO',3:'JR',4:'SR'}[yr] || 'SR',
        age: p.age, bat_hand: p.bat_hand, pitch_hand: p.pitch_hand,
        height: p.height, weight: p.weight,
        recruit_stars: p.recruit_stars || 0,
        is_injured: p.is_injured || false,
        pitch1_name: p.pitch1_name, pitch2_name: p.pitch2_name,
        ratings: {
          contact: rat.contact_display, power: rat.power_display,
          speed: rat.speed_display, eye: rat.eye_display,
          pendurance: rat.pendurance_display, pgenctrl: rat.pgencontrol_display,
          throwpwr: rat.pthrowpower_display, sequencing: rat.psequencing_display,
          pickoff: rat.pickoff_display,
          sp_rating: rat.sp_rating, rp_rating: rat.rp_rating,
        },
        potentials: {
          pendurance: pot.pendurance_pot, pgenctrl: pot.pgencontrol_pot,
          throwpwr: pot.pthrowpower_pot, sequencing: pot.psequencing_pot,
          pickoff: pot.pickoff_pot, contact: pot.contact_pot,
          power: pot.power_pot, speed: pot.speed_pot,
        }
      };
    }).sort((a, b) => (b.ovr || 0) - (a.ovr || 0));

    const games = (raw.AllGames || [])
      .sort((a, b) => a.week - b.week || (a.game_day||'').localeCompare(b.game_day||''))
      .map(g => {
        const isHome = g.home_team_id === TEAM;
        const oppId  = isHome ? g.away_team_id : g.home_team_id;
        const opp    = teamMap[oppId] || {};
        return {
          id: g.id, week: g.week, game_day: g.game_day || 'a',
          is_complete: !!g.is_complete, is_home: isHome,
          bama_score: isHome ? g.home_score : g.away_score,
          opp_score:  isHome ? g.away_score : g.home_score,
          won: g.is_complete ? (g.winning_team_id === TEAM) : null,
          opp_abbrev: opp.team_abbrev || '?',
          opp_name:   opp.team_full_name || '?',
          opp_conf:   opp.conference || '',
          is_sec:     opp.conference === SEC,
          game_type:  g.game_type || 'regular',
        };
      });

    const allSt = raw.Standings || [];
    const bamaSt = allSt.find(s => s.team_id === TEAM) || {};
    const secSt  = allSt
      .filter(s => s.conference === SEC && s.team_level === 3)
      .sort((a, b) => b.wins - a.wins || a.losses - b.losses);

    const ctx = raw.SeasonContext || {};
    return {
      updated_at: new Date().toISOString(),
      week: ctx.current_week_index || 1,
      season_year: ctx.league_year || 2026,
      record:      { wins: bamaSt.wins || 0, losses: bamaSt.losses || 0 },
      conf_record: { wins: bamaSt.conf_wins || 0, losses: bamaSt.conf_losses || 0 },
      standing: bamaSt, roster, games, sec_standings: secSt,
    };
  }

  // ── Utilities ─────────────────────────────────────────────────────────────

  function numToGrade(n) {
    if (n == null) return '?';
    if (n >= 90) return 'A+'; if (n >= 85) return 'A';  if (n >= 80) return 'A-';
    if (n >= 75) return 'B+'; if (n >= 70) return 'B';  if (n >= 65) return 'B-';
    if (n >= 60) return 'C+'; if (n >= 55) return 'C';  if (n >= 50) return 'C-';
    if (n >= 45) return 'D+'; if (n >= 40) return 'D';  if (n >= 35) return 'D-';
    return 'F';
  }

  function gradeClass(g) {
    if (!g || g === '?' || g === 'N') return 'g-f';
    const u = g.toUpperCase();
    if (u === 'A+')  return 'g-ap'; if (u === 'A')  return 'g-a';  if (u === 'A-') return 'g-am';
    if (u === 'B+')  return 'g-bp'; if (u === 'B')  return 'g-b';  if (u === 'B-') return 'g-bm';
    if (u === 'C+')  return 'g-cp'; if (u === 'C')  return 'g-c';  if (u === 'C-') return 'g-cm';
    if (u.startsWith('D')) return 'g-dp';
    return 'g-f';
  }

  function gradeColor(g) {
    if (!g || g === '?' || g === 'N') return '#666';
    const u = g.toUpperCase();
    if (u.startsWith('A')) return '#22c55e';
    if (u.startsWith('B')) return '#60a5fa';
    if (u.startsWith('C')) return '#f59e0b';
    if (u.startsWith('D')) return '#f87171';
    return '#dc2626';
  }

  function gradeCell(g) {
    const safe = g || '?';
    return `<span class="grade ${gradeClass(safe)}">${safe}</span>`;
  }

  function ovrChip(g) {
    const safe = g || '?';
    return `<span class="ovr-chip ${gradeClass(safe)}">${safe}</span>`;
  }

  function clsPill(yr_label) {
    const map = { FR:'cls-fr', SO:'cls-so', JR:'cls-jr', SR:'cls-sr' };
    return `<span class="cls-pill ${map[yr_label]||'cls-sr'}">${yr_label}</span>`;
  }

  function classBadge(yr_label) {
    const map = { FR:'cls-fr', SO:'cls-so', JR:'cls-jr', SR:'cls-sr' };
    return `<span class="class-badge ${map[yr_label]||'cls-sr'}">${yr_label}</span>`;
  }

  function fmtHeight(in_) {
    if (!in_) return '–';
    return `${Math.floor(in_ / 12)}'${in_ % 12}"`;
  }

  function stars(n) {
    const full = Math.min(5, n || 0);
    return '<span style="color:#f59e0b;font-size:10px">'
      + '★'.repeat(full) + '<span style="color:#444">' + '★'.repeat(5 - full) + '</span></span>';
  }

  function ts(updated_at) {
    const d = updated_at ? new Date(updated_at) : new Date();
    return d.toLocaleString('en-US', { month:'short', day:'numeric', hour:'numeric', minute:'2-digit', hour12:true });
  }

  function loading(id) {
    const el = document.getElementById(id);
    if (el) el.innerHTML = '<div style="text-align:center;padding:40px;color:#888;font-size:13px">Loading live data…</div>';
  }

  function stamp(id, updated_at) {
    const el = document.getElementById(id);
    if (el) el.textContent = `Live · ${ts(updated_at)}`;
  }

  // ── Render: Live Status Bar (index + war-room) ─────────────────────────────

  function renderStatusBar(data, containerId) {
    const el = document.getElementById(containerId);
    if (!el || !data) return;
    const r  = data.record;
    const cr = data.conf_record;
    const st = data.standing;
    const injured = (data.roster || []).filter(p => p.is_injured).length;
    const fr_count = (data.roster || []).filter(p => p.year_label === 'FR').length;
    el.innerHTML = `
<div class="live-bar">
  <div class="live-bar-item">
    <div class="live-bar-val">${r.wins}–${r.losses}</div>
    <div class="live-bar-lbl">Overall</div>
  </div>
  <div class="live-bar-sep"></div>
  <div class="live-bar-item">
    <div class="live-bar-val">${cr.wins}–${cr.losses}</div>
    <div class="live-bar-lbl">SEC Record</div>
  </div>
  <div class="live-bar-sep"></div>
  <div class="live-bar-item">
    <div class="live-bar-val">${st.games_back != null ? (st.games_back === 0 ? '—' : st.games_back) : '—'}</div>
    <div class="live-bar-lbl">GB in SEC</div>
  </div>
  <div class="live-bar-sep"></div>
  <div class="live-bar-item">
    <div class="live-bar-val">Wk ${data.week}</div>
    <div class="live-bar-lbl">Current Week</div>
  </div>
  <div class="live-bar-sep"></div>
  <div class="live-bar-item">
    <div class="live-bar-val">${(data.roster||[]).length}</div>
    <div class="live-bar-lbl">Roster Size</div>
  </div>
  <div class="live-bar-sep"></div>
  <div class="live-bar-item">
    <div class="live-bar-val">${injured > 0 ? injured : '0'}</div>
    <div class="live-bar-lbl">Injured</div>
  </div>
</div>`;
  }

  // ── Render: Depth Chart ────────────────────────────────────────────────────

  function renderDepthChart(data, panelsId, hdrSubId, hdrStatsId) {
    const el = document.getElementById(panelsId);
    if (!el || !data) return;

    const roster = data.roster || [];
    const seniors = roster.filter(p => p.year_label === 'SR');
    const pitchers = roster.filter(p => p.ptype === 'Pitcher');
    const starters = pitchers.filter(p => p.pos === 'SP').sort((a,b) => (b.ovr||0)-(a.ovr||0));
    const relievers = pitchers.filter(p => p.pos !== 'SP').sort((a,b) => (b.ovr||0)-(a.ovr||0));
    const hitters = roster.filter(p => p.ptype !== 'Pitcher').sort((a,b) => (b.ovr||0)-(a.ovr||0));

    if (document.getElementById(hdrSubId)) {
      document.getElementById(hdrSubId).textContent =
        `${roster.length} players · ${pitchers.length} pitchers · ${hitters.length} position players · ${seniors.length} graduating seniors`;
    }
    if (document.getElementById(hdrStatsId)) {
      const elite = roster.filter(p => (p.ovr||0) >= 80).length;
      document.getElementById(hdrStatsId).innerHTML = `
        <div class="hdr-stat"><div class="hdr-stat-num" style="color:#22c55e">${elite}</div><div class="hdr-stat-lbl">80+ OVR Players</div></div>
        <div class="hdr-stat"><div class="hdr-stat-num" style="color:#f08898">${seniors.length}</div><div class="hdr-stat-lbl">Graduating</div></div>
        <div class="hdr-stat"><div class="hdr-stat-num" style="color:#fbbf24">${roster.filter(p=>p.year_label==='FR').length}</div><div class="hdr-stat-lbl">Freshmen</div></div>`;
    }

    const pitcherRow = (p, i) => {
      const isSr = p.year_label === 'SR';
      const pitches = [p.pitch1_name, p.pitch2_name].filter(Boolean).join(' / ') || '–';
      return `<tr>
        <td class="row-num">${i+1}</td>
        <td><span class="pname${isSr?' pname-grad':''}">${p.firstname} ${p.lastname}</span>${p.is_injured?' <span style="color:#f87171;font-size:10px">INJ</span>':''}</td>
        <td>${p.pos}</td>
        <td class="c">${ovrChip(p.ovr_grade)}</td>
        <td>${clsPill(p.year_label)}</td>
        <td>${p.pitch_hand || '?'}</td>
        <td class="cell-note">${pitches}</td>
      </tr>`;
    };

    const hitterRow = (p, i) => {
      const isSr = p.year_label === 'SR';
      const rat = p.ratings || {};
      return `<tr>
        <td class="row-num">${i+1}</td>
        <td><span class="pname${isSr?' pname-grad':''}">${p.firstname} ${p.lastname}</span>${p.is_injured?' <span style="color:#f87171;font-size:10px">INJ</span>':''}</td>
        <td>${p.pos}</td>
        <td class="c">${ovrChip(p.ovr_grade)}</td>
        <td>${clsPill(p.year_label)}</td>
        <td>${(p.bat_hand||'?')}/${(p.pitch_hand||'?')}</td>
        <td class="cell-note">${[rat.contact && 'CON:'+rat.contact, rat.power && 'PWR:'+rat.power].filter(Boolean).join(' ')}</td>
      </tr>`;
    };

    el.innerHTML = `
<!-- STARTING PITCHERS -->
<div class="panel">
  <div class="panel-hdr">
    <span class="panel-title">Starting Rotation</span>
    <span class="panel-count">${starters.length} SP</span>
  </div>
  <div class="table-scroll">
    <table class="data-table">
      <thead><tr><th>#</th><th>Player</th><th>Pos</th><th class="c">OVR</th><th>Class</th><th>Arm</th><th>Pitches</th></tr></thead>
      <tbody>${starters.map(pitcherRow).join('') || '<tr><td colspan="7" style="color:#888;padding:16px">No starters on roster</td></tr>'}</tbody>
    </table>
  </div>
</div>

<!-- BULLPEN -->
<div class="panel">
  <div class="panel-hdr">
    <span class="panel-title">Bullpen</span>
    <span class="panel-count">${relievers.length} RP</span>
  </div>
  <div class="table-scroll">
    <table class="data-table">
      <thead><tr><th>#</th><th>Player</th><th>Pos</th><th class="c">OVR</th><th>Class</th><th>Arm</th><th>Pitches</th></tr></thead>
      <tbody>${relievers.map(pitcherRow).join('') || '<tr><td colspan="7" style="color:#888;padding:16px">No relievers on roster</td></tr>'}</tbody>
    </table>
  </div>
</div>

<!-- POSITION PLAYERS -->
<div class="panel" style="grid-column:1/-1">
  <div class="panel-hdr">
    <span class="panel-title">Position Players</span>
    <span class="panel-count">${hitters.length} Players</span>
  </div>
  <div class="table-scroll">
    <table class="data-table">
      <thead><tr><th>#</th><th>Player</th><th>Pos</th><th class="c">OVR</th><th>Class</th><th>B/T</th><th>Key Ratings</th></tr></thead>
      <tbody>${hitters.map(hitterRow).join('') || '<tr><td colspan="7" style="color:#888;padding:16px">No position players on roster</td></tr>'}</tbody>
    </table>
  </div>
</div>`;
  }

  // ── Render: Schedule ──────────────────────────────────────────────────────

  function renderSchedule(data, containerId, statsId) {
    const el = document.getElementById(containerId);
    if (!el || !data) return;

    const games = data.games || [];
    const wins   = games.filter(g => g.is_complete && g.won).length;
    const losses = games.filter(g => g.is_complete && !g.won).length;
    const upcoming = games.filter(g => !g.is_complete).length;

    if (document.getElementById(statsId)) {
      document.getElementById(statsId).innerHTML = `
        <div class="stat-box"><div class="val">${wins}–${losses}</div><div class="lbl">Record</div></div>
        <div class="stat-box"><div class="val">${upcoming}</div><div class="lbl">Games Left</div></div>
        <div class="stat-box"><div class="val">${games.filter(g=>g.is_sec&&g.is_complete&&g.won).length}–${games.filter(g=>g.is_sec&&g.is_complete&&!g.won).length}</div><div class="lbl">SEC Record</div></div>
        <div class="stat-box"><div class="val">Wk ${data.week}</div><div class="lbl">Current Week</div></div>`;
    }

    // Group by week
    const byWeek = {};
    for (const g of games) {
      if (!byWeek[g.week]) byWeek[g.week] = [];
      byWeek[g.week].push(g);
    }

    const resultBadge = (g) => {
      if (!g.is_complete) return '<span style="color:#888;font-size:11px">Upcoming</span>';
      const color = g.won ? '#22c55e' : '#f87171';
      const label = g.won ? 'W' : 'L';
      return `<span style="color:${color};font-weight:900;font-size:13px">${label}</span> <span style="color:#888;font-size:12px">${g.bama_score}–${g.opp_score}</span>`;
    };

    const typeBadge = (g) => {
      if (g.game_type === 'playoff' || g.game_type === 'tournament') return '<span class="type-badge" style="background:rgba(245,158,11,0.15);color:#f59e0b;border:1px solid rgba(245,158,11,0.3)">TOURN</span>';
      if (g.is_sec) return '<span class="type-badge type-sec">SEC</span>';
      return '<span class="type-badge type-nc">Non-Conf</span>';
    };

    const rows = Object.keys(byWeek).sort((a,b) => +a - +b).flatMap(wk => {
      const wGames = byWeek[wk];
      const isCurrent = +wk === data.week;
      return wGames.map((g, i) => {
        const loc = g.is_home ? '<span class="home-badge">vs</span>' : '<span class="away-badge">@</span>';
        const rowClass = isCurrent ? ' class="sec-row"' : (g.is_sec ? ' class="sec-row"' : '');
        return `<tr${rowClass}>
          <td class="week">${i === 0 ? wk : ''}</td>
          <td>${loc}${g.opp_name}</td>
          <td>${resultBadge(g)}</td>
          <td>${typeBadge(g)}</td>
        </tr>`;
      });
    });

    el.innerHTML = `
<div class="month-block">
  <div class="month-label">Full Season Schedule — Week by Week</div>
  <div class="table-scroll">
    <table>
      <thead><tr><th>Wk</th><th>Opponent</th><th>Result</th><th>Type</th></tr></thead>
      <tbody>${rows.join('')}</tbody>
    </table>
  </div>
</div>`;
  }

  // ── Render: Pitcher Potentials ─────────────────────────────────────────────

  function renderPitcherTable(data, tbodyId) {
    const el = document.getElementById(tbodyId);
    if (!el || !data) return;

    const pitchers = (data.roster || [])
      .filter(p => p.ptype === 'Pitcher')
      .sort((a, b) => {
        if (a.pos === 'SP' && b.pos !== 'SP') return -1;
        if (a.pos !== 'SP' && b.pos === 'SP') return 1;
        return (b.ovr || 0) - (a.ovr || 0);
      });

    const roleLabel = (p) => {
      const ovr = p.ovr || 0;
      if (p.pos === 'SP') {
        if (ovr >= 80) return '<span class="role-badge role-ace">ACE STARTER</span>';
        return '<span class="role-badge role-starter">STARTER</span>';
      }
      if (ovr >= 75) return '<span class="role-badge role-closer">CLOSER</span>';
      if (ovr >= 65) return '<span class="role-badge role-setup">SETUP</span>';
      if (ovr >= 55) return '<span class="role-badge role-mid">MID REL</span>';
      return '<span class="role-badge role-dev">LONG/DEV</span>';
    };

    el.innerHTML = pitchers.map(p => {
      const isSr  = p.year_label === 'SR';
      const pot   = p.potentials || {};
      const ovr   = p.pos === 'SP' ? numToGrade(p.ratings?.sp_rating) : numToGrade(p.ratings?.rp_rating);
      return `<tr${isSr?' class="grad-row"':''}>
        <td><span class="player-name">${p.firstname} ${p.lastname}</span>${p.is_injured?' <span style="color:#f87171;font-size:10px">INJ</span>':''}</td>
        <td>${classBadge(p.year_label)}</td>
        <td class="center">${gradeCell(ovr)}</td>
        <td class="center">${gradeCell(pot.pendurance)}</td>
        <td class="center">${gradeCell(pot.pgenctrl)}</td>
        <td class="center">${gradeCell(pot.throwpwr)}</td>
        <td class="center">${gradeCell(pot.sequencing)}</td>
        <td class="center">${gradeCell(pot.pickoff)}</td>
        <td>${roleLabel(p)}</td>
      </tr>`;
    }).join('');
  }

  // ── Render: SEC Standings ─────────────────────────────────────────────────

  function renderStandings(data, containerId) {
    const el = document.getElementById(containerId);
    if (!el || !data) return;
    const rows = data.sec_standings || [];
    const bamaRow = (s) => s.team_abbrev === 'BAMA';

    el.innerHTML = `
<div class="panel" style="grid-column:1/-1;margin-bottom:20px">
  <div class="panel-hdr">
    <span class="panel-title">SEC Standings &mdash; ${data.season_year}</span>
    <span class="panel-count">Week ${data.week}</span>
  </div>
  <div class="table-scroll">
    <table class="data-table">
      <thead><tr>
        <th>#</th><th>Team</th><th class="c">W</th><th class="c">L</th>
        <th class="c">PCT</th><th class="c">SEC W</th><th class="c">SEC L</th><th class="c">GB</th>
      </tr></thead>
      <tbody>${rows.map((s,i) => `<tr${bamaRow(s)?' style="background:rgba(158,27,50,0.12)"':''}>
        <td class="row-num">${i+1}</td>
        <td><span class="pname${bamaRow(s)?' pname-grad':''}">${s.team_abbrev}</span></td>
        <td class="c">${s.wins}</td>
        <td class="c">${s.losses}</td>
        <td class="c">${(+s.win_pct||0).toFixed(3)}</td>
        <td class="c">${s.conf_wins}</td>
        <td class="c">${s.conf_losses}</td>
        <td class="c">${s.games_back === 0 ? '—' : s.games_back}</td>
      </tr>`).join('')}
      </tbody>
    </table>
  </div>
</div>`;
  }

  // ── Render: Freshmen ──────────────────────────────────────────────────────

  function renderFreshmen(data, containerId) {
    const el = document.getElementById(containerId);
    if (!el || !data) return;
    const freshmen = (data.roster || []).filter(p => p.year_label === 'FR');
    if (!freshmen.length) { el.innerHTML = '<p style="color:#888;font-size:13px">No freshmen on current roster.</p>'; return; }

    const pitchers  = freshmen.filter(p => p.ptype === 'Pitcher').sort((a,b)=>(b.ovr||0)-(a.ovr||0));
    const hitters   = freshmen.filter(p => p.ptype !== 'Pitcher').sort((a,b)=>(b.ovr||0)-(a.ovr||0));

    const card = (p) => {
      const pot  = p.potentials || {};
      const rat  = p.ratings   || {};
      const isPitcher = p.ptype === 'Pitcher';
      const key1  = isPitcher ? ['Endurance', pot.pendurance] : ['Contact',  pot.contact];
      const key2  = isPitcher ? ['Control',   pot.pgenctrl]   : ['Power',    pot.power];
      const key3  = isPitcher ? ['Velocity',  pot.throwpwr]   : ['Speed',    pot.speed];
      return `<div class="fr-card">
        <div class="fr-card-top">
          <div class="fr-accent"></div>
          <div class="fr-meta">${p.pos} &bull; ${isPitcher ? (p.pitch_hand||'R') + 'HP' : (p.bat_hand||'?') + '/' + (p.pitch_hand||'?')} &bull; Age ${p.age}</div>
          <div class="fr-name">${p.firstname} ${p.lastname}</div>
          <div class="fr-tags">
            <span class="ftag ftag-blue">${p.pos}</span>
            <span class="ftag ftag-green">FR · ${p.recruit_stars}★</span>
            ${p.is_injured ? '<span class="ftag" style="background:rgba(248,113,113,0.15);color:#f87171;border:1px solid rgba(248,113,113,0.3)">INJ</span>' : ''}
          </div>
        </div>
        <div class="fr-card-body">
          <div class="fr-stats-grid">
            <div class="fr-stat"><div class="fr-stat-lbl">OVR</div><div class="fr-stat-val" style="color:${gradeColor(p.ovr_grade)}">${p.ovr_grade}</div></div>
            <div class="fr-stat"><div class="fr-stat-lbl">${key1[0]}</div><div class="fr-stat-val" style="color:${gradeColor(key1[1])}">${key1[1]||'?'}</div></div>
            <div class="fr-stat"><div class="fr-stat-lbl">${key2[0]}</div><div class="fr-stat-val" style="color:${gradeColor(key2[1])}">${key2[1]||'?'}</div></div>
            <div class="fr-stat"><div class="fr-stat-lbl">${key3[0]}</div><div class="fr-stat-val" style="color:${gradeColor(key3[1])}">${key3[1]||'?'}</div></div>
          </div>
        </div>
        <div class="fr-card-foot">${fmtHeight(p.height)} · ${p.weight || '–'} lbs · ${stars(p.recruit_stars)}</div>
      </div>`;
    };

    el.innerHTML = `
<div class="section-label">Live Freshman Class &mdash; ${freshmen.length} Players</div>
<div class="fr-grid">
  ${pitchers.concat(hitters).map(card).join('')}
</div>`;
  }

  // ── Public API ────────────────────────────────────────────────────────────

  return {
    load,
    renderStatusBar, renderDepthChart, renderSchedule,
    renderPitcherTable, renderStandings, renderFreshmen,
    stamp, loading, numToGrade, gradeClass, gradeColor, gradeCell, ovrChip,
    clsPill, classBadge, fmtHeight, stars, ts,
  };
})();
